name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore "ASP.NET_Core/FoodOrdering.API/FoodOrdering.API.csproj"
    - name: Build
      run: dotnet build "ASP.NET_Core/FoodOrdering.API/FoodOrdering.API.csproj" --no-restore   
